# Generated by Django 3.2.13 on 2022-07-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fileobject_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschangelog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
