# Generated by Django 3.2.13 on 2022-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupclient',
            name='login',
        ),
        migrations.RemoveField(
            model_name='backupclient',
            name='password',
        ),
        migrations.AddField(
            model_name='backupclient',
            name='config',
            field=models.TextField(default=None, verbose_name='RClone config'),
            preserve_default=False,
        ),
    ]
