# Generated by Django 3.2.13 on 2022-06-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_auto_20220529_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupclient',
            name='client_name',
            field=models.CharField(choices=[('yandex_drive', 'Yandex Drive'), ('mailru_cloud', 'Mailru Cloud'), ('google_drive', 'Google drive')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RCloneProvider',
        ),
    ]
