# Generated by Django 3.2.13 on 2022-06-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_alter_backupclient_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('container_creating_started', 'Container creating started'), ('container_created', 'Archive created'), ('uploading_container_to_storage', 'Uploading container to storage'), ('container_uploaded_to_storage', 'Container uploaded to storage'), ('done', 'Done'), ('failed', 'Failed')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='backupclient',
            name='client_name',
            field=models.CharField(choices=[('yandex_drive', 'Yandex Drive'), ('mailru_cloud', 'Mailru Cloud'), ('google_drive', 'Google drive'), ('dump_database', 'Dump database'), ('local_container', 'Local container')], max_length=255),
        ),
    ]
