# Generated by Django 3.2.13 on 2022-06-12 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backup', '0005_auto_20220604_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthTemporaryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('state', models.CharField(max_length=255, verbose_name='Oauth state')),
                ('oauth_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_temp_states', to='backup.backupclient', verbose_name='Oauth client')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Oauth temp state',
                'verbose_name_plural': 'Oauth temp states',
                'ordering': ('-created_at',),
            },
        ),
    ]
