# Generated by Django 3.2.13 on 2022-06-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0008_backupclient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupclient',
            name='status',
            field=models.CharField(choices=[('credentials_not_confirmed', 'Credentials not confirmed'), ('credentials_confirmed', 'Credentials confirmed')], default='credentials_not_confirmed', max_length=255),
        ),
    ]
