# Generated by Django 3.2.13 on 2022-06-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0009_alter_backupclient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtemporarystate',
            name='status',
            field=models.CharField(choices=[('in_awaiting', 'In awaiting'), ('expired', 'Expired'), ('success', 'Success')], default='in_awaiting', max_length=255),
        ),
    ]
