# Generated by Django 3.2.13 on 2022-06-12 06:08

from django.db import migrations, models
import helpers.utils


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0010_alter_oauthtemporarystate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtemporarystate',
            name='state',
            field=models.CharField(default=helpers.utils.get_uuid_hex_state, max_length=255, verbose_name='Oauth state'),
        ),
    ]
