# Generated by Django 3.2.13 on 2022-06-12 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backup', '0011_alter_oauthtemporarystate_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupClientTemporaryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('state', models.CharField(default=helpers.utils.get_uuid_hex_state, max_length=255, verbose_name='State')),
                ('status', models.CharField(choices=[('in_awaiting', 'In awaiting'), ('expired', 'Expired'), ('success', 'Success')], default='in_awaiting', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_states', to='backup.backupclient', verbose_name='Backup client')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Backup client temp state',
                'verbose_name_plural': 'Backup clients temp states',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='OauthTemporaryState',
        ),
        migrations.AddIndex(
            model_name='backupclienttemporarystate',
            index=models.Index(fields=['state'], name='backup_back_state_913e3a_idx'),
        ),
    ]
