# Generated by Django 3.2.13 on 2022-07-24 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0013_auto_20220723_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceforbackup',
            name='status_logs',
        ),
    ]
